version: '3'
services:
  app:
    container_name: simple-hapi
    restart: always
    build: .
    ports:
      - '3000:9000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
